### ISSUE TITLE
Humanoid Robotics - Presentation Thread

### ISSUE THREAD

**Issue by sprince0031** [sprince0031/UL_Masters#37]
## Decide on the 4 topics of choice and list below

**Comment by pk-verma** [comment]
- Soft Robotics
- Human-humanoid Interaction

**Comment by sprince0031** [comment]
1. Evolving Robot Swarms and Groups
2. Motion Planning and Gait Generation in Humanoid Robots

**Comment by sprince0031** [comment]
Order of preference for the topics based on random coin flips :
1. Human-humanoid Interaction
2. Evolving Robot Swarms and Groups
3. Motion Planning and Gait Generation in Humanoid Robots
4. Soft Robotics

**Comment by sprince0031** [comment]
We've been assigned the topic, "Evolving Robot Swarms and Groups".

Team members:
- @pk-verma 
- Karthik
- Helena
- @sprince0031 

We can use the issue thread to keep a track of notes/to-dos/gotchas etc.

**Comment by sprince0031** [comment]
## Project notes
( Courtesy of Helena :D )

![IMG-20231113-WA0010.jpg](https://github.com/sprince0031/UL_Masters/assets/19924682/8301a1f5-9ae9-4430-8247-62d0d1f800a3)

**Comment by osullh** [comment]
Here's a link to the Google Drive I created for the Research Project:
https://drive.google.com/drive/folders/1pVIUwFrp7ypn6QJU_Bs5Du_a-M7JwgTp

Also, since we are using IEEE citations for the paper, here's a link to the reference generator site we could use: https://www.mybib.com/tools/ieee-citation-generator

**Comment by sprince0031** [comment]
### Regarding Webots for the sim
I have created a Webots project locally to learn how to create a virtual world. I've started small with a single robot. I'm working on how to implement the robot swarm part. I'll post further updates by today.

**Comment by sprince0031** [comment]
## Reference book:
Attaching a pdf of the book, "Evolutionary Swarm Robotics" for our reference.

@pk-verma @osullh @karthikcrazy37

[978-3-540-77612-3.pdf](https://github.com/sprince0031/UL_Masters/files/13479128/978-3-540-77612-3.pdf)

**Comment by sprince0031** [comment]
We're done with CS6271 (hopefully!)
